### PR TITLE
Load API_KEY from django project settings in __init__.py

### LINKED ISSUE #9: Load TMDb API key from config file
Right now MM2 can only load a TMDb API key from the environment variable `MM2_TMDB_API_KEY`. There should be some to load the key from a config file. The config file should be in a proper data serialization format in case other settings might be loaded from it in the future. I'm liking JSON for this just because that would mean avoiding additional dependencies even though it isn't as human-readable/editable as, say, YAML.

### PR DESCRIPTION
**Pull request by Math-ias**
Now you must apply the API_KEY in your django project settings.py
instead of the environment.
NOTE: However that run_tests.py still loads it from the environment,
there is not a solution for this yet. run_tests.py might be temp.
broken from this fix ...
Closes #9

### CODE REVIEW

**Comment by simon-andrews** [comment]
Suggestion: use the `or` feature for variable declarations so that compatibility with environment variables isn't broken. This will make it so that it will accept the first possible valid value.

Example:

``` python
x = 5 or None        # 5
x = None or 5        # 5
x = 5 or 6           # 5
x = 6 or 5           # 6
x = 5 or 'a' or True # 5
```

**Comment by simon-andrews** [comment]
Also you can change the Django settings for the test suite in [tests/test_settings.py](https://github.com/simon-andrews/movieman2/blob/master/tests/test_settings.py).

**Comment by Math-ias** [comment]
The build is currently not passing. I added the features you requested, it ran on my computer but I don't think I did test_settings.py correctly.

**Comment by Math-ias** [comment]
I have realized that the builds are failing as my pull request doesn't have the environment variable being set for it. Therefore we are getting key errors.

EDIT: Sorry for the crapton of commits, I kept forgetting to add things in my commits, it's very dirt, apologies.

**Comment by Math-ias** [comment]
I will rewrite a pull request. Try again!

**Pull request closed without merging**
